pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}    
  - name: automatic merge if author is javiyt
    conditions:
        - author=javiyt
        - status-success=Travis CI - Pull Request
        - base=master
    actions:
      merge:
        method: squash    
      delete_head_branch: {}    
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}    